{% set name = "chezmoi" %}
{% set version = "2.59.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twpayne/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 577bce7c9038ca17cda2c61c1ff3df90c4b366b68629e3056e274cf4b319be30

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://chezmoi.io
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  dev_url: https://github.com/twpayne/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
