{% set name = "chezmoi" %}
{% set version = "2.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twpayne/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 70a077c9be09fc3f7dd684ab9f80c85f60702fea881789b7fb1b9b9b08bce275

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses < 1.1

test:
  commands:
    - {{ name }} --help

about:
  home: https://chezmoi.io
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  dev_url: https://github.com/twpayne/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
