{% set name = "chezmoi" %}
{% set version = "2.52.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twpayne/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0bfe878d901f5e171cfcab7bd4d647f3fbf7f882be9bf747fabe188a9815e91c

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://chezmoi.io
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  dev_url: https://github.com/twpayne/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
