{% set name = "chezmoi" %}
{% set version = "2.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/twpayne/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d8f553d871d35caf3d446b6f1032f4cad81a75fc41955bd3d71216a2aa6e17a4

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://chezmoi.io
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  dev_url: https://github.com/twpayne/{{ name }}

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
