schema_version: 1

context:
  version: "2.69.0"

package:
  name: chezmoi
  version: ${{ version }}

source:
  url: https://github.com/twpayne/chezmoi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 37d99b5551c5a8cf82c2efcf5f9510e8784d46497fb4bde3fedc0ceac5b78c5f

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - chezmoi --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  homepage: https://chezmoi.io
  repository: https://github.com/twpayne/chezmoi

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
