schema_version: 1

context:
  version: 2.68.0

package:
  name: chezmoi
  version: ${{ version }}

source:
  url: https://github.com/twpayne/chezmoi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: accd6f9a982f9066ea8dbf385f5c68be869ac1e883d7e1faa9997194a7ad2982

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - chezmoi --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  homepage: https://chezmoi.io
  repository: https://github.com/twpayne/chezmoi

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
