schema_version: 1

context:
  version: "2.72.1"

package:
  name: chezmoi
  version: ${{ version }}

source:
  url: https://github.com/twpayne/chezmoi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 52a2fbff0c11285bac91b9267bce0f48069153c111890debf61836953dfcbca8

build:
  number: 1

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      content:
        - chezmoi --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  homepage: https://chezmoi.io
  repository: https://github.com/twpayne/chezmoi

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
