schema_version: 1

context:
  version: "2.70.2"

package:
  name: chezmoi
  version: ${{ version }}

source:
  url: https://github.com/twpayne/chezmoi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 4dfacb37e1f6714305d7c8570bc25880342dfddbe81259c9253a5881de035321

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - chezmoi --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  homepage: https://chezmoi.io
  repository: https://github.com/twpayne/chezmoi

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
