schema_version: 1

context:
  version: "2.72.2"

package:
  name: chezmoi
  version: ${{ version }}

source:
  url: https://github.com/twpayne/chezmoi/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 977c779f616ebf3d49700ceca426d61f367e2850ff397d3ae95ca32d7f954309

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      content:
        - chezmoi --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Manage your dotfiles across multiple diverse machines, securely
  homepage: https://chezmoi.io
  repository: https://github.com/twpayne/chezmoi

extra:
  recipe-maintainers:
    - anjos
    - danielnachun
